# Generated by Django 4.0.6 on 2022-07-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhanvien', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NhanVien',
            new_name='ThemMoiNV',
        ),
    ]
